# Generated by Django 3.2.7 on 2023-02-09 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('complaint', models.TextField()),
                ('sentiment', models.CharField(blank=True, max_length=20, null=True, verbose_name='sentiment category')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
